import asyncio
import os
import httpx
import pandas as pd
from bs4 import BeautifulSoup
from tqdm.asyncio import tqdm

INPUT_FILE  = "missing_urls.csv"   # generated by compare_urls.py
OUTPUT_FILE = "medicine_details_full.csv"

CONCURRENCY = 50
BATCH_SIZE = 500
RETRY_LIMIT = 3

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
}


# ---------------------------
# AUTO RESUME INDEX
# ---------------------------
def get_start_from(output_file):
    if not os.path.exists(output_file):
        return 0
    try:
        return len(pd.read_csv(output_file))
    except Exception:
        return 0


# ---------------------------
# RESUME LOGIC
# ---------------------------
def get_remaining_urls(input_file, output_file):
    # missing_urls.csv has a single "url" column produced by compare_urls.py
    df = pd.read_csv(input_file)
    col = "url" if "url" in df.columns else df.columns[0]
    all_urls = df[col].dropna().tolist()

    try:
        done_urls = set(pd.read_csv(output_file)["url"].dropna().tolist()) if os.path.exists(output_file) else set()
    except Exception:
        done_urls = set()

    remaining = [u for u in all_urls if u not in done_urls]
    print(f"Missing URLs loaded : {len(all_urls)}")
    print(f"Already saved       : {len(done_urls)}")
    print(f"To scrape           : {len(remaining)}")
    return remaining


# ---------------------------
# TEXT CLEANER
# ---------------------------
def clean_text(text):
    if not text:
        return None
    skip = {"USES OF", "BENEFITS OF", "SIDE EFFECTS OF"}
    seen, cleaned = set(), []
    for line in text.split("\n"):
        line = line.strip()
        if any(kw in line for kw in skip):
            continue
        if line not in seen and len(line) > 3:
            seen.add(line)
            cleaned.append(line)
    return " ".join(cleaned) or None


# ---------------------------
# HTML PARSER
# ---------------------------
def parse_page(url, html):
    soup = BeautifulSoup(html, "lxml")

    name = soup.find("h1")
    name = name.text.strip() if name else None

    def get_after_label(label):
        tag = soup.find(lambda t: t.name == "div" and t.get_text(strip=True) == label)
        if tag:
            sibling = tag.find_next_sibling("div")
            if sibling:
                a = sibling.find("a")
                return a.text.strip() if a else sibling.get_text(strip=True)
        return None

    def extract_section(section_id):
        section = soup.find(id=section_id)
        if not section:
            return None
        content = section.find(class_=lambda c: c and "content" in c)
        return clean_text((content or section).get_text("\n"))

    img = soup.find("img", src=lambda s: s and "onemg" in s)

    return {
        "url": url,
        "name": name,
        "marketer": get_after_label("MARKETER"),
        "composition": get_after_label("SALT COMPOSITION"),
        "uses": extract_section("uses_and_benefits"),
        "side_effects": extract_section("side_effects"),
        "image_url": img["src"] if img else None,
    }


# ---------------------------
# ASYNC FETCH WITH RETRY
# ---------------------------
async def fetch(client, sem, url, pbar):
    async with sem:
        for attempt in range(RETRY_LIMIT):
            try:
                r = await client.get(url, timeout=20)
                if r.status_code == 200:
                    result = parse_page(url, r.text)
                    pbar.update(1)
                    return result
                elif r.status_code == 429:
                    await asyncio.sleep(2 ** attempt)
                else:
                    pbar.update(1)
                    return {"url": url, "error": f"HTTP {r.status_code}"}
            except Exception:
                await asyncio.sleep(1)
        pbar.update(1)
        return {"url": url, "error": "Failed after retries"}


# ---------------------------
# ASYNC WRITER
# ---------------------------
async def writer_task(queue, output_file):
    batch = []
    write_header = not os.path.exists(output_file)
    while True:
        item = await queue.get()
        if item is None:
            break
        if not item.get("error"):
            batch.append(item)
        if len(batch) >= BATCH_SIZE:
            df = pd.DataFrame(batch).drop_duplicates(subset=["url"])
            df.to_csv(output_file, mode="a", header=write_header, index=False)
            write_header = False
            total_saved = get_start_from(output_file)
            tqdm.write(f"\U0001f4be Batch saved — {total_saved} rows in CSV so far")
            batch = []
    # flush remaining batch no matter what
    if batch:
        df = pd.DataFrame(batch).drop_duplicates(subset=["url"])
        df.to_csv(output_file, mode="a", header=write_header, index=False)
        total_saved = get_start_from(output_file)
        tqdm.write(f"\U0001f4be Final batch saved — {total_saved} rows in CSV")


# ---------------------------
# MAIN
# ---------------------------
async def run():
    urls = get_remaining_urls(INPUT_FILE, OUTPUT_FILE)
    if not urls:
        print("All data already scraped.")
        return

    sem = asyncio.Semaphore(CONCURRENCY)
    write_queue = asyncio.Queue()

    with tqdm(total=len(urls), unit="url", dynamic_ncols=True, colour="green") as pbar:
        async with httpx.AsyncClient(headers=HEADERS, follow_redirects=True) as client:
            writer = asyncio.create_task(writer_task(write_queue, OUTPUT_FILE))
            tasks = [fetch(client, sem, url, pbar) for url in urls]

            try:
                for coro in asyncio.as_completed(tasks):
                    result = await coro
                    await write_queue.put(result)
            except (KeyboardInterrupt, asyncio.CancelledError):
                print("\n⚠ Interrupted! Flushing current batch to CSV...")
            finally:
                # always runs — flushes whatever is in the queue before exit
                await write_queue.put(None)
                await writer
                saved = get_start_from(OUTPUT_FILE)
                print(f"✅ Saved so far: {saved} rows. Next run will resume from index {saved}.")

    print("\nDONE ✔")


if __name__ == "__main__":
    asyncio.run(run())